#!/bin/bash
#/usr/local/sbin/mount-shared-folders
#echo "[i] Updating argos pannel"
#mv /root/.config/argos/tun0_status.0r.3s.sh /root/.config/argos/tun0_status.1r.3s.sh
#mv /root/.config/argos/tun0_status.1r.3s.sh /root/.config/argos/tun0_status.0r.3s.sh
echo "[i] Removing old folders and files"
vmware-hgfsclient | while read folder; do
	rm -rf "~/${folder}"
	rm -rf "~/Desktop/${folder}"
	rm -rf "/usr/local/sbin/htb-vpn"
	rm -rf "/${folder}"
 	echo "[i] Mounting ${folder}   (/mnt/hgfs/${folder})"
 	mkdir -p "/mnt/hgfs/${folder}"
 	umount -f "/mnt/hgfs/${folder}" 2>/dev/null
 	vmhgfs-fuse -o allow_other -o auto_unmount ".host:/${folder}" "/mnt/hgfs/${folder}"
 	echo "[i] Creating symlinks"
 	ln -s "/mnt/hgfs/${folder}" "~/${folder}"
 	ln -s "/mnt/hgfs/${folder}" "~/Desktop/${folder}"
 	ln -s "/mnt/hgfs/${folder}/#trainings/htb/info/htb-vpn.sh" "/usr/local/sbin/htb-vpn"
 	ln -s "/mnt/hgfs/${folder}/" "/${folder}"
done
echo [+] Done!
sleep 2s
